#!/usr/bin/env python3
"""Generate the SI's front cross-reference table: every headline quantity in the
main text, the SI section that derives it, and the results file that produced
it.

WHY THIS IS GENERATED. The advisor's 2026-09-05 letter, point 4.6: a referee
judges an SI by whether it can be walked, and this SI's sections already say
which main-text section each supports, but nothing anywhere says which file a
given number came out of. Writing that mapping by hand would produce a table
that is right on the day it is written. So each row here names a file AND a
path inside it, and the script refuses to emit the table unless every path
resolves and every quoted value still matches. A row that has gone stale fails
the build instead of misleading a referee.

WHAT A ROW IS.

    (main-text quantity, main-text §, SI §, results file, path, expected)

`path` is dotted, with list indices in brackets, and `expected` may be None
when the row points at a file rather than at a single number. Tolerance is
relative and deliberately loose at 2e-4, because the table prints rounded
values and the point of the check is provenance, not a fifth decimal place.

    python scripts/si_crossref.py            # rewrite the block in the SI
    python scripts/si_crossref.py --check    # verify only, exit 1 on drift
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SI = f"{ROOT}/paper/manuscript_JRSI_SI.md"
BEGIN = "<!-- BEGIN si-crossref: generated by scripts/si_crossref.py -->"
END = "<!-- END si-crossref -->"

# (quantity as the main text states it, main §, SI §, results file, path, expected)
ROWS = [
    ("10 186 891 962 rows, 79 months, 424 dong", "2.1", "§2",
     "results_inventory.json", "parquet_rows", 10186891962),
    ("the mask removes 26.1% of cells", "2.1", "§2",
     "results_p2.json", "cell_vs_volume_total.seoul_internal_cell_rate",
     0.26134826878687434),
    ("masked cells hold 2.27 people, not 1.5", "2.2", "§2",
     "results_p29.json", "202012.per_cell_mean", 2.2672850885038986),
    ("self-pairing moves the excess by −4.29%", "2.3", "§2",
     "results_p49.json", "primary.rel_change", -0.042854),
    ("mean cell occupancy, 1 080", "4.2", "§2",
     "results_p49.json", "sizes.cell_mean", 1080.4729),
    ("coverage profile, w̄ = 4.716", "2.4", "§4",
     "results_p33.json", "profile.wbar", 4.716),
    ("dong assortativity, 0.02115", "3.2", "§3",
     "results_p26.json", "matrices.202312|WE|dong|holidayfree.assortativity",
     0.02115385938228908),
    ("the Seoul survey's 0.2227", "3.2", "§3",
     "results_p39.json", "published_constants.survey", 0.22270993081818996),
    ("residual to best rank one, 0.1433", "3.2", "§3",
     "results_p32.json",
     "spectrum.passive|202312|WE|dong|holidayfree.best_rank1_resid", 0.1433),
    ("residual to the null, 0.1447", "3.2", "§3",
     "results_p32.json",
     "spectrum.passive|202312|WE|dong|holidayfree.pm_rank1_resid", 0.14474),
    ("distance between the two, 0.02573", "3.2", "§3",
     "results_p67.json", "summary.gap_rel_max", 0.02573),
    ("the crossing under the survey's pairing convention, 0.918", "3.3", "§7",
     "results_p69.json", "beta_star.realised_C", 0.9182),
    ("the Seoul arm's bound under it, 0.2318", "3.3", "§7",
     "results_p69.json", "answer.primary_reading.bound_C", 0.2318),
    ("17 months clear the 0.02296 floor", "3.1", "§5",
     "results_p54.json", "corrected.n_at_or_above", 17),
    ("true labelling survives 74 months, k = 12", "3.1", "§5",
     "results_p58.json", "degeneracy.mod12_zero_shifts.12", 74),
    ("chance agreement, 36.5 months", "3.1", "§5",
     "results_p58.json", "degeneracy.chance_agreement", 36.46835443037975),
    ("twelve distinct calendars", "3.1", "§5",
     "results_p64.json", "effective_alignments.E_exact", 12),
    ("district merge retains 29.8%", "3.3", "§6",
     "results_p37.json", "ladder.kept_median", 0.298378),
    ("16-band median, 0.019377", "3.3", "§6",
     "results_p60.json", "summary.r16.median", 0.01937665599076202),
    ("three-band median, 0.082904", "3.3", "§6",
     "results_p60.json", "summary.lim3.median", 0.08290387617137414),
    ("median monthly ratio, 3.9577", "3.3", "§6",
     "results_p60.json", "axis_asymmetry.age_3_over_16.median",
     3.9576547104079243),
    ("recovery surface and its inversion", "3.3", "§7",
     "results_p39.json", "inversion.{0.95}.bound_corrected",
     0.18476779889798053),
    ("realised β, and β\\* = 0.923", "3.3", "§7",
     "results_p66.json", "beta_star.realised_A", None),
    ("the twelve readings of β", "3.3", "§7",
     "results_p59.json", "claim.measured_betas", None),
    ("device sampling noise, 0.00439", "3.2", "§8",
     "results_p33.json",
     "R1_effective_sample.202312.stats.assortativity.noise_bias",
     0.0043860558176699906),
    ("coverage spans 14.0x the mask band", "3.4", "§8",
     "results_p33.json", "mask_vs_coverage.202312.ratio", 14.049528608891974),
    ("5 of 20 verdicts clear their null", "3.4", "§9",
     "results_p52.json", "answer.n_flips", 5),
]

TOL = 2e-4


def resolve(obj, path):
    """Walk a dotted path with bracketed list indices. Keys may contain dots
    only if they contain no '.', which is why the split is on '.' and the
    pipe-delimited cell keys survive: they hold no dots."""
    cur = obj
    # {...} protects a key that itself contains a dot, which p39's inversion
    # keys do: they are the beta values, "0.95" and "0.99".
    parts, buf, depth = [], "", 0
    for ch in path:
        if ch == "{":
            depth += 1
            continue
        if ch == "}":
            depth -= 1
            continue
        if ch == "." and depth == 0:
            parts.append(buf)
            buf = ""
            continue
        buf += ch
    parts.append(buf)
    for part in parts:
        m = re.match(r"^([^\[]*)((?:\[\d+\])*)$", part)
        key, idx = m.group(1), m.group(2)
        if key:
            if not isinstance(cur, dict) or key not in cur:
                raise KeyError(f"{path}: no key {key!r}")
            cur = cur[key]
        for i in re.findall(r"\[(\d+)\]", idx):
            cur = cur[int(i)]
    return cur


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    cache, bad, lines = {}, [], []
    for label, sec, si, fname, path, expected in ROWS:
        if fname not in cache:
            p = f"{ROOT}/eda/{fname}"
            if not os.path.exists(p):
                bad.append(f"{label}: {fname} does not exist")
                continue
            with open(p) as fh:
                cache[fname] = json.load(fh)
        try:
            got = resolve(cache[fname], path)
        except (KeyError, IndexError, TypeError) as e:
            bad.append(f"{label}: {e}")
            continue
        if expected is not None:
            if not isinstance(got, (int, float)) or isinstance(got, bool):
                bad.append(f"{label}: {path} is {type(got).__name__}, not a number")
                continue
            if abs(got - expected) > abs(expected) * TOL + 1e-12:
                bad.append(f"{label}: {path} is {got!r}, table says {expected!r}")
                continue
        lines.append(f"| {label} | §{sec} | {si} | `{fname}` |")

    if bad:
        print("cross-reference rows that no longer resolve:", file=sys.stderr)
        for b in bad:
            print(f"  {b}", file=sys.stderr)
        return 1

    table = "\n".join([
        BEGIN,
        "",
        "**Table S0. Where each headline number comes from.** One row per "
        "quantity the main text states, the section of this document that "
        "derives it, and the file under `eda/` that produced it. The table is "
        "generated by `scripts/si_crossref.py`, which reads each value back "
        "out of the named file and fails rather than print a row that has "
        "gone stale.",
        "",
        "| Quantity in the main text | Main text | This document | Produced by |",
        # PROPORTIONAL DASHES, NOT FOUR EQUAL RUNS. pandoc reads a pipe
        # table's column widths off the separator row, so "|---|---|---|---|"
        # gives each column a quarter of the text block and a 25-character
        # monospace filename then runs 18pt past its cell. The widths below
        # are the ones that fit the longest cell in each column.
        "|--------------------------------------|------|------|--------------------------------|",
        *lines,
        "",
        END,
    ])

    with open(SI, encoding="utf-8") as fh:
        s = fh.read()
    if BEGIN in s and END in s:
        s2 = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), table, s,
                    flags=re.S)
    else:
        anchor = "## 1. Extended related work"
        assert anchor in s, "the SI no longer opens with §1, so there is no "\
                            "unambiguous place to put the table"
        s2 = s.replace(anchor, table + "\n\n" + anchor, 1)

    if args.check:
        ok = s2 == s
        print(f"{len(lines)} rows verified; SI block "
              f"{'is current' if ok else 'is STALE, re-run without --check'}")
        return 0 if ok else 1

    with open(SI, "w", encoding="utf-8") as fh:
        fh.write(s2)
    print(f"{len(lines)} rows verified and written into {SI}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
